# Generated by Django 4.1.1 on 2023-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('married', models.BooleanField()),
                ('age', models.IntegerField()),
                ('GPA', models.FloatField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, max_length=20)),
                ('birth_data', models.DateField()),
                ('hamada', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
