# Generated by Django 4.1.1 on 2023-04-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_phonenumber_hobby_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamada',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
