# Generated by Django 4.1.1 on 2023-04-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_hamada'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('GPA__lte', 4)), name='gpa must be less than 4'),
        ),
    ]
